
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise2l2e5-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-pod
  template:
    metadata:
      labels:
        app: example-pod
    spec:
      containers:
      - name: exercise2l2e5
        image: l2e5_web
        command: ["docker build -t l2e5 ."]
        args: []
        env:
        - name: ENV_NAME
          value: “Env value”
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32323
  selector:
    app: example-pod
# The apiVersion defining the the deployment
# Defining Which Kubernetes Resource to use
# Metadata for the Deployment
# Name of Deployment

# Number of replicas


# This label serves as a reference to pod(s)
# Template for the Pod(s) to run
# Metadata for the Pod(s)

# Label matching the matchLabel.


# Name of the Pods
# Image running in the Pods
# Command to run
# Command arguments (and options)
# List of environment variables



# Port to expose
# This ‘---’  serves as the separation.





# Type of the service

# Cluster IP port to map to
# Containerport to map from
# Mapping to all nodes on port [30000:32767]

# This label serves as a reference to pod(s)
