# L5E5.yml
apiVersion: apps/v1    
kind: Deployment       
metadata:
  name: [NAME]
spec:
  selector:
    matchLabels:       
      component: [LABEL]
  replicas: 1
  template:
    metadata:
      labels:
        component: [LABEL]
    spec:
      containers:
        - name: spekt8
          image: ahmadhamid/spekt8
          ports:
            - containerPort: 3000